<?php
// ============================================
// Faraj Fruit Supplier and Vendor
// Week 4 – Task 1: Server-Side Processing
// Dynamic Welcome Page
// ============================================

$name    = '';
$message = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name    = htmlspecialchars($_POST['username']);
    $message = "Welcome to Faraj, " . $name . "! 🍊";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Welcome – Faraj</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=DM+Sans:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/faraj/assets/css/style.css">
</head>
<body>

<header>
  <div class="logo">🍊 Faraj Fruit Supplier</div>
  <nav>
    <a href="/faraj/index.php">Home</a>
    <a href="login.php">Login</a>
  </nav>
</header>

<div style="max-width:500px;margin:80px auto;padding:0 20px;">
  <div style="background:white;border-radius:14px;padding:40px;box-shadow:0 4px 20px rgba(0,0,0,0.08);border:1px solid #e0e0e0;">

    <div style="text-align:center;margin-bottom:24px;">
      <div style="font-size:48px;margin-bottom:12px;">🍊</div>
      <h2 style="font-family:'Playfair Display',serif;color:#1a5c2e;font-size:24px;">Server-Side Demo</h2>
      <p style="color:#888;font-size:14px;">Week 4 – Task 1: PHP Form Processing</p>
    </div>

    <?php if ($message): ?>
    <div style="background:#e8f5ec;border-left:5px solid #2e8b4a;padding:16px 20px;border-radius:8px;margin-bottom:24px;text-align:center;">
      <p style="color:#1a5c2e;font-weight:700;font-size:18px;"><?= $message ?></p>
      <p style="color:#555;font-size:13px;margin-top:6px;">This message was generated by PHP on the server using $_POST data.</p>
    </div>
    <?php endif; ?>

    <!-- PHP Code Demo Box -->
    <div style="background:#1a1a2e;border-radius:8px;padding:16px;margin-bottom:20px;">
      <p style="color:#f0a500;font-size:11px;font-family:monospace;margin-bottom:8px;">// PHP Processing Code (Week 4 – Task 1)</p>
      <p style="color:#a8e6bf;font-size:12px;font-family:monospace;line-height:1.8;">
        $name = $_POST['username'];<br>
        echo "Welcome " . $name;
      </p>
    </div>

    <form method="POST">
      <div style="margin-bottom:16px;">
        <label style="display:block;font-size:13px;font-weight:600;margin-bottom:6px;color:#444;">Enter Your Name</label>
        <input type="text" name="username" placeholder="e.g. Faraj Ahmed" required
          style="width:100%;padding:10px 14px;border:1px solid #e0e0e0;border-radius:8px;font-size:14px;font-family:'DM Sans',sans-serif;">
      </div>
      <button type="submit" class="btn btn-primary" style="width:100%;">Submit – See PHP Response</button>
    </form>

    <p style="text-align:center;margin-top:16px;font-size:12px;color:#888;">
      This demonstrates the <strong>Request → Server → Response</strong> cycle
    </p>
  </div>
</div>

<?php include 'includes/footer.php'; ?>
